import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('le polish éditorial garde le lookbook et les transitions réversibles', () => {
  const shop = readFileSync(new URL('../src/sections/shop/Shop.jsx', import.meta.url), 'utf8')
  const home = readFileSync(new URL('../src/pages/HomePage.jsx', import.meta.url), 'utf8')
  const about = readFileSync(new URL('../src/sections/about/About.jsx', import.meta.url), 'utf8')
  const styles = readFileSync(new URL('../src/styles/sections.css', import.meta.url), 'utf8')

  assert.doesNotMatch(shop, /product-folio/)
  assert.doesNotMatch(styles, /\.product-folio\s*\{/)
  assert.match(home, /section-bridge--music-about/)
  assert.match(home, /section-bridge--gallery-live/)
  assert.match(home, /section-bridge--live-shop/)
  assert.match(home, /section-bridge--music-about[\s\S]*?<Stars color="red" className="section-bridge-stars" \/>/)
  assert.match(home, /section-bridge--live-shop[\s\S]*?<Stars color="red" className="section-bridge-stars" \/>/)
  assert.match(home, /<div className="section-bridge section-bridge--gallery-live" aria-hidden="true" \/>/)
  assert.match(about, /<div className="section-bridge section-bridge--about-gallery" aria-hidden="true" \/>/)
  assert.match(styles, /\.section-bridge--about-gallery\s*\{[\s\S]*?height:\s*clamp\(16px, 1\.75vw, 24px\)/)
  assert.match(styles, /\.section-bridge--music-about,[\s\S]*?\.section-bridge--live-shop\s*\{[\s\S]*?height:\s*0;[\s\S]*?background:\s*transparent;/)
  assert.match(styles, /\.section-bridge--music-about::before,[\s\S]*?\.section-bridge--live-shop::before\s*\{[\s\S]*?content:\s*none;[\s\S]*?display:\s*none;/)
  assert.match(styles, /\.section-bridge--music-about::after,[\s\S]*?\.section-bridge--live-shop::after\s*\{[\s\S]*?width:\s*clamp\(7rem, 10vw, 9rem\);[\s\S]*?height:\s*1px;[\s\S]*?background:\s*linear-gradient/)
  assert.match(styles, /\.section-bridge-stars\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?left:\s*50%;[\s\S]*?top:\s*50%;/)
  assert.match(styles, /@keyframes doya-bridge-stars[\s\S]*?transform:\s*translate\(-50%, -50%\) scale\(\.992\);[\s\S]*?transform:\s*translate\(-50%, -50%\) scale\(1\.008\);/)
  assert.match(styles, /\.section-bridge--about-gallery::before,[\s\S]*?\.section-bridge--gallery-live::after\s*\{[\s\S]*?content:\s*none;[\s\S]*?display:\s*none;/)
  assert.match(styles, /@media \(max-width: 767px\)[\s\S]*?\.section-bridge--music-about,[\s\S]*?\.section-bridge--live-shop\s*\{[\s\S]*?height:\s*0;/)
  assert.match(styles, /@media \(max-width: 767px\)[\s\S]*?\.section-bridge--about-gallery,[\s\S]*?\.section-bridge--gallery-live\s*\{[\s\S]*?height:\s*13px;/)
  assert.match(styles, /grid-template-columns:\s*repeat\(12, minmax\(0, 1fr\)\)/)
  assert.match(styles, /@media \(min-width: 1200px\)[\s\S]*?\.products\s*\{[\s\S]*?align-items:\s*stretch;/)
  assert.match(styles, /\.products > \.product,[\s\S]*?\.products > \.product\.is-featured[\s\S]*?grid-column:\s*span 6;/)
  assert.match(styles, /\.products > \.product \.product-image-trigger,[\s\S]*?\.products > \.product\.is-featured \.product-image-trigger[\s\S]*?aspect-ratio:\s*16 \/ 10;/)
  assert.match(styles, /\.product\.is-featured\s*\{[\s\S]*?border-color:\s*rgb\(194 5 15 \/ 34%\);/)
  assert.match(styles, /\.product\.is-featured::after\s*\{[\s\S]*?transform:\s*scaleX\(1\);/)
  assert.match(styles, /\.product\.is-featured \.product-image\s*\{[\s\S]*?max-width:\s*min\(95%, 35rem\);/)
  assert.match(styles, /@media \(max-width: 767px\)[\s\S]*?\.product\.is-featured\s*\{[\s\S]*?border-color:\s*rgb\(194 5 15 \/ 32%\);/)
  assert.match(styles, /@media \(max-width: 767px\)[\s\S]*?\.product\.is-featured::after\s*\{[\s\S]*?transform:\s*scaleX\(1\);/)
  assert.match(styles, /@media \(max-width: 767px\)[\s\S]*?\.product\.is-featured \.product-image\s*\{[\s\S]*?max-width:\s*96%;/)
  assert.match(styles, /\.shop-section \.product\.is-featured \.product-buy\s*\{[\s\S]*?margin-top:\s*16px;/)
  assert.match(styles, /@media \(min-width: 1800px\)[\s\S]*?\.products > \.product,[\s\S]*?\.products > \.product\.is-featured[\s\S]*?grid-column:\s*span 6;/)
  assert.doesNotMatch(styles, /grid-column:\s*span 7;/)
  assert.doesNotMatch(styles, /grid-column:\s*span 5;/)
  assert.match(styles, /@keyframes doya-fashion-atmosphere/)
  assert.match(styles, /@keyframes doya-lookbook-light/)
  assert.match(styles, /@keyframes doya-bridge-stars/)
  assert.match(styles, /\.section-bridge-stars\s*\{/)
  assert.match(styles, /@media \(min-width: 1101px\)[\s\S]*?\.music-section\s*\{[\s\S]*?height:\s*auto;[\s\S]*?max-height:\s*none;/)
  assert.match(styles, /\.section-bridge-stars\s*\{[\s\S]*?width:\s*clamp\(22px, 1\.8vw, 27px\)/)
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/)
})
